### ISSUE TITLE
events.js:160     throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by uzzal2k5** [pol-is/polis-issues#108]
Please sort me about bellow error I faced. I do not find any file named events.js where should it be

```
sh-4.3# sh x
Running node v6.2.0
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE 127.0.0.1:5002
    at Object.exports._errnoException (util.js:953:11)
    at exports._exceptionWithHostPort (util.js:976:20)
    at Server._listen2 (net.js:1253:14)
    at listen (net.js:1289:10)
    at net.js:1399:9
    at GetAddrInfoReqWrap.asyncCallback [as callback] (dns.js:65:16)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:84:10)
SERVICE_URL: https://preprod.pol.is
sh-4.3# 
```

**Comment by metasoarous** [comment]
For which project is this?

**Comment by colinmegill** [comment]
Not a polis error. This occurs when you are trying to use the same port
twice, usually occurs if you have the process continuing to run in the
background / different tab.

**Comment by patcon** [comment]
Going to close this as resolved. Thanks for filing tickets @uzzal2k5!
